name: SpringBoot Deploy to AWS EC2

env:
  RESOURCE_PATH: ./backend/project/src/main/resources/application.yaml
  working-directory: ./backend/project

on:
  push:
    branches: [ "develop"]
    paths: 
       - 'backend/project/**'
       - '.github/workflows/be.yml'
  pull_request:
    branches: [ "develop"]
    paths: 
       - 'backend/project/**'
       - '.github/workflows/be.yml'

permissions:
  contents: read

jobs:
  build:        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set yaml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.RESOURCE_PATH }}
      env:
        spring.datasource.username: ${{ secrets.RDS_ID }}
        spring.datasource.password: ${{ secrets.RDS_SECRETS }}
        
    - name: Grant execute permission for gradlew
      working-directory: ${{env.working-directory}}
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      working-directory: ${{env.working-directory}}
      run: ./gradlew build -x test
      
    - name: Make Directory
      run: mkdir -p deploy
      working-directory: ${{env.working-directory}}
    
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      working-directory: ${{env.working-directory}}
    
    - name: Make zip file
      run: zip -r -qq -j ./my-lguplus-back.zip ./deploy
      working-directory: ${{env.working-directory}}
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 ./my-lguplus-back.zip s3://uplus-be/
      working-directory: ${{env.working-directory}}
