name: FE Dockerize and Deploy

env:
  working-directory: ./frontend/project

on:
   push:
     branches: [ "develop" ]
     paths: 
        - '.github/workflows/react-2.yml'
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CI: false
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v3      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

