name: React Deploy to AWS EC2

env:
  working-directory: ./frontend/project

on:
  push:
    branches: [ "develop" ]
    paths: 
       - 'frontend/project/**'
       - '.github/workflows/react.yml'
  pull_request:
    branches: [ "develop" ]
    paths:
       - 'frontend/project/**'
       - '.github/workflows/react.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CI: false
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v3      

    - name: Install Yarn
      run: npm install -g yarn
      working-directory: ${{env.working-directory}}
      
    - name: Install dependencies
      run: yarn install
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: yarn build
      working-directory: ${{env.working-directory}}

    - name: zip create 
      run: zip -qq -r ./my-lguplus-front.zip ./build
      shell: bash
      working-directory: ${{env.working-directory}}
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 ./my-lguplus-front.zip s3://uplus-be/
      working-directory: ${{env.working-directory}}
      
    - name: Deploy to AWS CodeDeploy
      run: aws deploy create-deployment 
        --application-name my-lguplus-web-deploy
        --deployment-group-name my-lguplus-web-deploy-group
        --file-exists-behavior OVERWRITE 
        --s3-location bucket=uplus-be,bundleType=zip,key=my-lguplus-front.zip
        --region ap-northeast-2
