# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React build

on:
  push:
    branches: [ "develop" ]
    paths: 
       - 'frontend/project/**'
       - '.github/workflows/react.yml'
  pull_request:
    branches: [ "develop" ]
    paths:
       - 'frontend/project/**'
       - '.github/workflows/react.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    
    env:
      CI: false
    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: "frontend/project"
        
    steps:
    - uses: actions/checkout@v3
    
    
#     - name: Use Node.js 12.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12.x
  
      
#     - name: Test
#       run: npm test
#       env:
#         CI: true

    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
      
    - name: Build                   # React Build
      run: yarn build

    - name: zip create 
      # zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
      run: zip -qq -r ./**build-fe.zip .**
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}
      
      # Upload build file to S3
    - name: Upload to S3 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
        
        
#     # GitHub Actions CLI 환경에서 S3 사용자 권한의 aws 접속
#     - name: Configure AWS credentials 
#       uses: aws-actions/configure-aws-credentials@v1 
#       with: 
#         aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }} 
#         aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }} 
#         aws-region: ap-northeast-2
