name: FE Dockerize and Deploy

env:
  working-directory: ./frontend/project

on:
   push:
     branches: [ "develop" ]
     paths: 
        - '.github/workflows/react-2.yml'
        - '.frontend/project'
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CI: false
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v3      

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: uplusizero/front
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{env.working-directory}}/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels}}
