name: FE Dockerize and Deploy

env:
  working-directory: ./frontend/project

on:
   push:
     branches: [ "develop" ]
     paths: 
        - '.github/workflows/react-2.yml'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
